fit:
  model:
    encoder_lr: 1e-5
    encoder_wd: 0
    decoder_lr: 2e-5
    decoder_wd: 0
    optimizer: adam,
    alpha: 
      -
      -
      -
      -
      -
      -
    normal_activation: normal_activation,
    fourier_activation: fourier_activation,
    eps: eps,
    momentum: momentum,
  data:
    batch_size: 4
  