trainer:
  logger: true
  enable_checkpointing: true
  max_epochs: 2500
  accelerator: cuda
  devices:  1
  precision: '32'

model:
  class_path: module.fourier_vae.models.FourierVAE
  dict_kwargs:
    encoder_lr: 1e-3
    encoder_wd: 0
    decoder_lr: 1e-4
    decoder_wd: 0
    alpha:
      - 0.011570737437682454
      - 0.001103484695815668
      - 0.013517931366753718
      - 0.01963144615407613
    normal_activation: silu
    fourier_activation: sigmoid
    eps: 0.1
    momentum: 0.1
    optimizer: adam
data:
  batch_size: 12

