trainer:
  logger: true
  enable_checkpointing: true
  max_epochs: 2500
  accelerator: cuda
  devices:  1
  precision: '32'

model:
  class_path: module.fourier_vae.models.FourierVAE
  dict_kwargs:
    encoder_lr: 1e-5
    encoder_wd: 0
    decoder_lr: 1e-6
    decoder_wd: 0
    alpha:
      - 0.008263758469562796
      - 0.07786649161694688
      - 0.09990505491458727
      - 0.05909958891548734
    normal_activation: silu
    fourier_activation: relu
    eps: 0.1  
    momentum: 0.1
    optimizer: adam
data:
  batch_size: 6

