fit:
  model:
    encoder_lr: 1e-5
    encoder_wd: 0
    decoder_lr: 2e-5
    decoder_wd: 0
    alpha_1: 6
    alpha_2: 8
    alpha_3: 0.05
    alpha_4: 4
    alpha_5: 6
    alpha_6: 0.1
  data:
    batch_size: 1
  